### ISSUE TITLE
Build error with "ui.gui.Execute undefined"

### ISSUE THREAD

**Issue by orumin** [esimov/diagram#1]
In now, this project has build error on "go get" command with below message:

```
src/github.com/esimov/diagram/ui/panels.go:241: ui.gui.Execute undefined (type *gocui.Gui has no field or method Execute)
src/github.com/esimov/diagram/ui/panels.go:467: ui.gui.Execute undefined (type *gocui.Gui has no field or method Execute)
src/github.com/esimov/diagram/ui/panels.go:610: ui.gui.Execute undefined (type *gocui.Gui has no field or method Execute)
```

this is caused by rename method in gocui.
https://github.com/jroimartin/gocui/commit/6564cfcacb01db61e3a4e983405a598db3e91982

**Comment by esimov** [comment]
Thanks for reporting. I fixed the issue. It was due to the undergone changes in the gocui library.
