### ISSUE TITLE
go get deprecated

### ISSUE THREAD

**Issue by HoloTheDrunk** [esimov/diagram#12]
It would seem like `go get` has been deprecated.
Tried installing using `go install github.com/esimov/diagram@latest` but that failed with the following output:
```
go: downloading github.com/esimov/diagram v1.0.5
go: github.com/esimov/diagram@latest (in github.com/esimov/diagram@v1.0.5):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```
I have never written a line of Go in my life so I can't really provide deeper insight.

**Comment by HoloTheDrunk** [comment]
Related but not the repository's fault: the AUR package is also broken due to this.

**Comment by esimov** [comment]
If there are replace or exclude directives in the module, you have to clone the source and afterwards install it.

```bash
$ git clone https://github.com/esimov/diagram
$ cd diagram
$ go install
````

The documentation is a little bit outdated but I will update it with the new instructions.
Also be aware that there are some dependencies required as it is mentioned in the Readme file.
