### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by setop** [esimov/diagram#14]
In order to make it work on Debian 11, I had to install many dependencies:

```
sudo apt-get install \
  libxcursor-dev \
  libxrandr-dev  \
  libxinerama-dev  \
  libgl-dev \
  libxi-dev \
  freeglut3-dev \
  libglu1-mesa-dev  \
  libglfw3-dev \
  libgles2-mesa-dev \
  libglu1-mesa-dev \
  mesa-common-dev \
  xorg-dev

go build
```

This may solve #9.

Plus I had to manually copy the font to the expected folder.

```
mkdir -p $HOME/go/src/github.com/esimov/diagram/font
cp font/gloriahallelujah.ttf $HOME/go/src/github.com/esimov/diagram/font/
```

Nice tool BTW !

**Comment by esimov** [comment]
All of the above dependencies are related to the go-glfw library. That's why it's also mentioned in the README file, that glfw is required in order to run this tool.

**Comment by esimov** [comment]
I'm welcoming you to create a PR and update the install section of the README file with your findings. Would you do it?
