### ISSUE TITLE
a linked package fails - wh

### ISSUE THREAD

**Issue by uhbiv** [esimov/diagram#2]
When doing a "go get", fogelman/gg, which is the API for rendering 2D gfx, fails to compile. How to overcome this?

![image](https://user-images.githubusercontent.com/553859/31514846-aef63144-afb0-11e7-9a4a-3ddccea5fdd2.png)

**Comment by esimov** [comment]
Can you check if you have installed `golang.org/x/image/`? I think this is the reason for the compilation error. I haven't included the dependent libraries into a vendor folder make the app more lightweight. Try to install it separately and let me know.
