### ISSUE TITLE
build fails with "fatal error: glfw/src/context.c: No such file or directory"

### ISSUE THREAD

**Issue by kortschak** [esimov/diagram#7]
As filed in #6, building diagram fails with a failure to find components from glfw, even when glfw is installed (though note that the README does not give instructions detailing deps for diagram).

This failure occurs with current Go releast go1.11.1 and with go1.9.7 which is approximately what is being tested on by this project at travis - [which also fails](https://travis-ci.org/esimov/diagram/jobs/413521999#L457-L461) in the same manner.

```
~ $ uname -a
Linux cube 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
~ $ go version
go version go1.9.7 linux/amd64
~ $ dpkg -l libglfw*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  libglfw3:amd64 3.1.2-3      amd64        portable library for OpenGL, wind
ii  libglfw3-dev:a 3.1.2-3      amd64        portable library for OpenGL, wind
```

```
~/src/github.com/esimov/diagram [master]$ go install
# github.com/esimov/diagram/vendor/github.com/go-gl/glfw/v3.2/glfw
vendor/github.com/go-gl/glfw/v3.2/glfw/c_glfw.go:4:30: fatal error: glfw/src/context.c: No such file or directory
compilation terminated.
```

Invoking `build.sh` also fails with the same error.

Maybe you are building glfw locally and this is the difference? But with the current instructions, this doesn't build.

**Comment by kortschak** [comment]
If I copy the directory of github.com/go-gl/glfw/v3.2/glfw/glfw into your vendor directory to the appropriate place from the commit specified in your Gopkg,lock then it builds. So it looks like you've not properly committed the vendored package there.

**Comment by esimov** [comment]
Hey @kortschak thanks for notifying me about this error and also for taking the effort to debug it. You was right that the reason for the compiler build error was the incorrect vendor dependency generated by go-dep. For some reason generating the dependency tree with `go-dep` resulted in a truncated glfw library, but copying manually the glfw library into the vendor folder resolved the issue.

I've updated the library with the corrected dependency tree.

Thanks, @esimov

**Comment by esimov** [comment]
Since i haven't received any feedback from my last update, i will close this ticket.

**Comment by kortschak** [comment]
Sorry about that. Yes, I can confirm this is fixed.
